/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'postcode' : string,
  'country' : string,
  'city' : string,
  'name' : string,
  'line1' : string,
  'line2' : string,
}
export interface Category { 'id' : bigint, 'name' : string }
export interface Coupon {
  'id' : bigint,
  'active' : boolean,
  'value' : bigint,
  'code' : string,
  'discountType' : string,
}
export interface GiftCard {
  'id' : bigint,
  'redeemedBy' : [] | [Principal],
  'active' : boolean,
  'balance' : bigint,
  'code' : string,
  'purchasedBy' : Principal,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'total' : bigint,
  'userId' : Principal,
  'discountAmount' : bigint,
  'createdAt' : bigint,
  'shippingCost' : bigint,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface PaymentInfo { 'method' : string, 'details' : string }
export interface Product {
  'id' : bigint,
  'categoryId' : bigint,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'price' : bigint,
}
export interface UserProfile { 'address' : Address }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string], undefined>,
  'createCoupon' : ActorMethod<[Coupon], undefined>,
  'createGiftCard' : ActorMethod<[string, bigint], undefined>,
  'createProduct' : ActorMethod<[Product], undefined>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCoupons' : ActorMethod<[], Array<Coupon>>,
  'getGiftCardByCode' : ActorMethod<[string], [] | [GiftCard]>,
  'getOrdersByUser' : ActorMethod<[], Array<Order>>,
  'getPaymentInfo' : ActorMethod<[], Array<PaymentInfo>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [Array<OrderItem>, bigint, bigint, bigint, bigint],
    undefined
  >,
  'redeemGiftCard' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPaymentInfo' : ActorMethod<[string, string], undefined>,
  'toggleCoupon' : ActorMethod<[bigint, boolean], undefined>,
  'updateCategory' : ActorMethod<[bigint, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'validateCoupon' : ActorMethod<[string], [] | [Coupon]>,
  'verifyStaffCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];