/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Coupon = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'value' : IDL.Nat,
  'code' : IDL.Text,
  'discountType' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'total' : IDL.Nat,
  'userId' : IDL.Principal,
  'discountAmount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'shippingCost' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const Address = IDL.Record({
  'postcode' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'address' : Address });
export const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const GiftCard = IDL.Record({
  'id' : IDL.Nat,
  'redeemedBy' : IDL.Opt(IDL.Principal),
  'active' : IDL.Bool,
  'balance' : IDL.Nat,
  'code' : IDL.Text,
  'purchasedBy' : IDL.Principal,
});
export const PaymentInfo = IDL.Record({
  'method' : IDL.Text,
  'details' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text], [], []),
  'createCoupon' : IDL.Func([Coupon], [], []),
  'createGiftCard' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getGiftCardByCode' : IDL.Func([IDL.Text], [IDL.Opt(GiftCard)], ['query']),
  'getOrdersByUser' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPaymentInfo' : IDL.Func([], [IDL.Vec(PaymentInfo)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'redeemGiftCard' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPaymentInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'toggleCoupon' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  'verifyStaffCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Coupon = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'value' : IDL.Nat,
    'code' : IDL.Text,
    'discountType' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'total' : IDL.Nat,
    'userId' : IDL.Principal,
    'discountAmount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'shippingCost' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const Address = IDL.Record({
    'postcode' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'address' : Address });
  const Category = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const GiftCard = IDL.Record({
    'id' : IDL.Nat,
    'redeemedBy' : IDL.Opt(IDL.Principal),
    'active' : IDL.Bool,
    'balance' : IDL.Nat,
    'code' : IDL.Text,
    'purchasedBy' : IDL.Principal,
  });
  const PaymentInfo = IDL.Record({ 'method' : IDL.Text, 'details' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text], [], []),
    'createCoupon' : IDL.Func([Coupon], [], []),
    'createGiftCard' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getGiftCardByCode' : IDL.Func([IDL.Text], [IDL.Opt(GiftCard)], ['query']),
    'getOrdersByUser' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPaymentInfo' : IDL.Func([], [IDL.Vec(PaymentInfo)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'redeemGiftCard' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPaymentInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'toggleCoupon' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
    'verifyStaffCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };